version: '3.3'

services:
   web-service:
     depends_on:
       - model-service
     image: schneli3/djl-serving-consumer:latest
     ports:
       - "80:8082"
     restart: always

   model-service:
     image: schneli3/djl-serving:latest
     restart: always
